# Generated by Django 4.0.3 on 2022-04-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='profile',
            new_name='organiser',
        ),
    ]
