# Generated by Django 4.0.4 on 2022-04-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_category_options_category_organiser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='base_app.category'),
        ),
    ]
